[dev]
  autoLaunch = false
  framework = "#custom"
  command = "npm run dev"
  targetPort = 8080

[[redirects]]
  from = "/:tag/:articleId/images/covers/:type.png"
  to = "/.netlify/functions/image"
  status = 200
